image:
  repository: cinetix/cinetix-platform/booking-service
  tag: "latest"

service:
  port: 8082

resources:
  requests:
    cpu: 200m
    memory: 384Mi
  limits:
    cpu: 1000m
    memory: 768Mi

extraEnv:
  - name: SPRING_PROFILES_ACTIVE
    value: k8s
  - name: DB_HOST
    value: postgres
  - name: DB_PORT
    value: "5432"
  - name: DB_NAME
    value: booking_db
  - name: RABBITMQ_HOST
    value: rabbitmq
  - name: REDIS_HOST
    value: redis
  - name: KEYCLOAK_URL
    value: http://keycloak:8080

extraEnvFrom:
  - secretRef:
      name: booking-service-secrets
