image:
  repository: cinetix/cinetix-platform/showtime-service
  tag: "latest"

service:
  port: 8083

grpc:
  enabled: true
  port: 9083

extraEnv:
  - name: SPRING_PROFILES_ACTIVE
    value: k8s
  - name: DB_HOST
    value: postgres
  - name: DB_PORT
    value: "5432"
  - name: DB_NAME
    value: showtime_db
  - name: RABBITMQ_HOST
    value: rabbitmq
  - name: REDIS_HOST
    value: redis
  - name: KEYCLOAK_URL
    value: http://keycloak:8080

extraEnvFrom:
  - secretRef:
      name: showtime-service-secrets
