global:
  scrape_interval: 15s

scrape_configs:
  - job_name: booking-service
    static_configs:
      - targets: ['booking-service:8082']
    metrics_path: /actuator/prometheus

  - job_name: showtime-service
    static_configs:
      - targets: ['showtime-service:8083']
    metrics_path: /actuator/prometheus

  - job_name: payment-service
    static_configs:
      - targets: ['payment-service:8086']
    metrics_path: /actuator/prometheus
